### ISSUE TITLE
Adding executionData to Notebook runs

### ISSUE THREAD

**Issue by domagoj-gusic-sb** [ambika-garg/apache-airflow-microsoft-fabric-plugin#1] opened 2024-07-23 12:06 UTC
In `run_fabric_item(self, workspace_id: str, item_id: str, job_type: str) ->` str method, I believe this is missing if compared to API:

- `executionData `-> https://learn.microsoft.com/en-us/rest/api/fabric/core/job-scheduler/run-on-demand-item-job?tabs=HTTP#request-body

When using `executionData`, you can send additional params to the notebook when you want to run it. Is it possible to add this? Right now, you can only "run" the Notebook which is fine, but this would allow for much greater flexibility.

**Comment by ambika-garg** [comment] 2024-08-07 15:47
Hey @domagoj-gusic-sb,
I noticed you created a separate package on PyPI: https://pypi.org/project/apache-airflow-microsoft-fabric-plugin-custom/. Could you please remove both the Power BI and Fabric plugins? They are misleading as I am actively managing these packages on behalf of Microsoft.
I would really appreciate it if you could raise a PR for any issues in the main repository. I’d be happy to review and merge your commits.
Thank you!

**Comment by ambika-garg** [comment] 2024-08-14 11:10
Hi @domagoj-gusic-sb,
The issue is now fully addressed in PR #4, and it has been merged. Thanks for bringing this up! If you need any more adjustments, just let me know—I’d be happy to help.
Kind regards,
Ambika

**Closed** 2024-08-14 11:10 UTC
